### ISSUE TITLE
problem with execute bernard installation in powershell (windows users)

### ISSUE THREAD

**Issue by majidzamanian** [mimseyedi/Bernard#2]
hello. in line 113 in file of Bernard_installation.py The System Cannot Find The File Specified becuse we run the 
" subprocess.call('clear' if os.name == 'posix' else 'cls') "
command in a window shell, but do not specify the shell=True argument in the subprocess module’s run method.
to correct this problem we must add shell=True in the methode
like this:

"subprocess.call('clear' if os.name == 'posix' else 'cls' , shell=True)"

**Comment by mimseyedi** [comment]
> hello. in line 113 in file of Bernard_installation.py The System Cannot Find The File Specified becuse we run the " subprocess.call('clear' if os.name == 'posix' else 'cls') " command in a window shell, but do not specify the shell=True argument in the subprocess module’s run method. to correct this problem we must add shell=True in the methode like this:
> 
> "subprocess.call('clear' if os.name == 'posix' else 'cls' , shell=True)"

Thank you very much for your participation.
Yes, this was a problem that I could not find, and thank you for your help.
As you said, the problem is solved by setting the shell parameter equal to the correct one.

subprocess.call('clear' if os.name == 'posix' else 'cls', shell=True)

thank you.
